version: '3.8'

services:
  mysqldb:
    build: ./database
    container_name: mysqldb_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: jokesdb
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  nodeapp:
    build: .
    container_name: jokeapplication_container
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management plugin port

  etl:
    build: ./etl
    container_name: etl_container
    depends_on:
      - rabbitmq
      - mysqldb

volumes:
  db_data: